Dockerfile

deploy : Dockerfile 수정

---

src/main/java/com/yedu/backend/domain/parents/domain/entity/Parents.java
src/main/resources/db/migration/V1_202502030415__create_teacher.sql

feat : flyway sql수정

---

src/main/java/com/yedu/backend/admin/application/dto/req/TeacherSearchRequest.java
src/main/java/com/yedu/backend/admin/presentation/AdminController.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java

요청시 지역 타입 변경
String -> District enum형식으로 변경

fix : 요청시 지역 타입 변경

---

src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingController.java
src/main/java/com/yedu/backend/global/config/security/SecurityConfig.java

HotFix : 권한 설정 수정

---

.github/workflows/CD-prod.yml
.github/workflows/CI-prod.yml

deploy : 운영 CI/CD 1차

---

src/main/java/com/yedu/backend/domain/teacher/application/dto/res/EnglishCurriculumResponse.java
src/main/java/com/yedu/backend/domain/teacher/application/dto/res/MathCurriculumResponse.java
src/main/java/com/yedu/backend/domain/teacher/application/mapper/TeacherMapper.java
src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherInfoUseCase.java
src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherController.java

fix : 영어, 수학 응답 분리 및 영상 추가

---

src/main/java/com/yedu/backend/admin/application/dto/res/AllFilteringTeacher.java
src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
src/main/java/com/yedu/backend/domain/matching/application/dto/res/ClassMatchingForTeacherResponse.java
src/main/java/com/yedu/backend/domain/matching/application/mapper/ClassMatchingMapper.java
src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassMatchingInfoUseCase.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherAvailableDslRepository.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherAvailableDslRepositoryImpl.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherAvailableRepository.java
src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherGetService.java

Fix/qa : QA 수정사항

---

src/main/java/com/yedu/backend/admin/domain/service/AdminGetService.java
src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingDslRepository.java
src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingDslRepositoryImpl.java
src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingRepository.java

fix : 알림톡 상태별 정렬

---

src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioSend.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioTeacherMessage.java

fix : 알림톡 관련 수정

---

src/main/java/com/yedu/backend/global/bizppurio/application/mapper/BizppurioMapper.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioSend.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioTeacherMessage.java

fix : WebClient요청 관련 수정

---

src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioParentsMessage.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioTeacherMessage.java

HotFix : WebClient 요청 관련 수정

---

src/main/java/com/yedu/backend/domain/matching/application/dto/res/ClassMatchingForTeacherResponse.java
src/main/java/com/yedu/backend/domain/matching/application/mapper/ClassMatchingMapper.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java

선생님 검색 및 선생님 금액 추가
- 선생님 검색시 '학과' 추가
- 선생님 수락 및 보류 페이지 금액 응답 추가

Fix/search 선생님 검색 및 선생님 금액 추가

---

src/main/java/com/yedu/backend/global/bizppurio/application/mapper/BizppurioMapper.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioSend.java

fix : 선생님 알림톡 내용 변경

---

src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java

feat : 로그 추가

---

src/main/java/com/yedu/backend/global/bizppurio/application/mapper/BizppurioMapper.java

feat : 템플릿 수정

---

src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java

fix : 테스트용 API 수정

---

src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java

fix : 알림톡 템플릿 변경

---

src/main/java/com/yedu/backend/global/bizppurio/application/mapper/BizppurioMapper.java

HotFix : 알림톡 템플릿 변경

---

src/main/java/com/yedu/backend/global/excel/application/usecase/ExcelManageUseCase.java

HotFix : 로그 추가

---

src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingDslRepositoryImpl.java

선생님 알림톡 전송 결과 정렬 수정
- 전송 -> 수락 -> 거절 -> 대기 순으로 수정

fix : 선생님 알림톡 전송 결과 정렬 수정

---

src/main/java/com/yedu/backend/admin/application/dto/res/AllFilteringTeacher.java
src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java

fix : 성별 추가

---

src/main/java/com/yedu/backend/domain/teacher/application/dto/req/AvailableChangeRequest.java
src/main/java/com/yedu/backend/domain/teacher/application/dto/req/DistrictChangeRequest.java
src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java
src/main/java/com/yedu/backend/domain/teacher/domain/entity/TeacherAvailable.java
src/main/java/com/yedu/backend/domain/teacher/domain/entity/TeacherDistrict.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherAvailableRepository.java
src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDistrictRepository.java
src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherDeleteService.java
src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherSaveService.java
src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherController.java
src/main/resources/db/migration/V2_202503121717__alter_createAndUpadateTime.sql

프론트 전달 API 완료
- 관련 테크스펙 링크 : https://www.notion.so/1b3afa1037b280bfa7d2ca1780e03b76
- 선생님 가능시간, 가능지역 테이블 생성일 및 수정일 추가
- 선생님 가능 시간 수정
- 선생님 가능 지역 수정

Feat/correctionTeacher 2차

---

src/main/java/com/yedu/backend/global/bizppurio/application/mapper/BizppurioMapper.java

feat : 알림톡 탬플릿 수정

---

src/main/java/com/yedu/backend/global/bizppurio/application/constant/BizppurioResponseCode.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioSend.java

refactor : 알림톡 예외 알림 템플릿 수정

---

src/main/java/com/yedu/backend/domain/matching/domain/entity/constant/MatchingStatus.java
src/main/resources/db/migration/V3_202504031746__alter_modify_status.sql

매칭 테이블 enum값 수정
매칭 테이블의 enum값에 대해 매칭, 최종매칭, 과외결렬을 추가했습니다.
flyway의 경우 V3(이번에 세번째 스프린트를 진행하며 변경해서 V3라고 명명함)날짜+시간__행위.sql 로 이름을 지어서 진행하면 될 것 같습니다.

feat : 매칭 테이블 enum값 수정

---

src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleConfirmRequest.java
src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleMatchingResponse.java
src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRefuseRequest.java
src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementKeyStorage.java
src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingScheduleController.java

- 관련 테크스펙 링크 : https://www.notion.so/REST-API-1cbafa1037b28007bd8ffbbbf0512e53
- API 이름 변경 (매칭 -> 상담)
- 상담 신행 API 응답 ID 값 타입 변경 (Long -> String UUID 토큰) : URL 만들때 사용한다고 전달받아 수정하였습니다~

refactor : 상담 신청 API 응답 필드 타입 수정

---

src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRetrieveRequest.java
src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRetrieveResponse.java
src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassManagementRepository.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementKeyStorage.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementQueryService.java
src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingScheduleController.java

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1cbafa1037b28007bd8ffbbbf0512e53&pm=s
- 제출 시점에 토큰 만료 로직 추가
- 상담 결과 조회 API 추가 (classMatchingId 또는 UUID토큰값으로 검색 가능)

feat : 상담 결과 조회 API 추가, 토큰 만료 로직 추가

---

src/main/java/com/yedu/backend/bizppurio/application/mapper/BizppurioMapper.java
src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioCheckStep.java
src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioParentsMessage.java
src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioSend.java
src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioTeacherMessage.java
src/main/java/com/yedu/backend/bizppurio/presentation/BizppurioController.java
src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
src/main/java/com/yedu/backend/global/event/dto/MatchingConfirmTeacherEvent.java
src/main/java/com/yedu/backend/global/event/dto/MatchingParentsEvent.java
src/main/java/com/yedu/backend/global/event/dto/ParentsClassInfoEvent.java
src/main/java/com/yedu/backend/global/event/dto/TeacherClassRemindEvent.java
src/main/java/com/yedu/backend/global/event/dto/TeacherExchangeEvent.java
src/main/java/com/yedu/backend/global/event/listener/BizppurioParentsMessageListener.java
src/main/java/com/yedu/backend/global/event/listener/BizppurioTeacherMessageListener.java
src/main/java/com/yedu/backend/global/event/mapper/EventMapper.java
src/main/java/com/yedu/backend/global/event/publisher/BizppurioEventPublisher.java

- 관련 테크스펙 링크 : https://www.notion.so/ApplicationEvent-1caafa1037b2802d8e32db4650861afd
- 알림톡 전송 템플릿 작성
https://www.notion.so/Case-Script-185afa1037b280229f72e104959ea92d
- 알림톡 전송시 순서를 반드시 보장해달라는 요청을 받아서, 관련해서 Redis 저장 후 웹훅으로 결과 나오면 확인 후 전송할 수 있도록 구현하였습니다.
- 알림톡 전송 이벤트를 위해 기존의 Service에서 ID로 반환하는 값을 ClassManagement 반환하도록 변경한 부분이 있습니다. (충돌 주의)
리마인드 알림톡과 템플릿 변수가 복잡한 알림톡 1개는 이후 작성하여 올리도록 하겠습니다
application.yml에 변경점이 생겼습니다!

feat : 알림톡 전송 step1

---

src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
src/main/java/com/yedu/backend/admin/application/usecase/AdminInfoUseCase.java
src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java

- 관련 테크스펙 링크 :  https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1cbafa1037b28007bd8ffbbbf0512e53&pm=s
- accept (수락) 조건 수정 : 수락/전송/매칭/최종매칭/과외결렬
- 불필요한 null 처리 제거 

accept count 조건 수정 

---

src/main/java/com/yedu/backend/admin/application/dto/res/AllApplicationResponse.java
src/main/java/com/yedu/backend/admin/application/dto/res/ClassDetailsResponse.java
src/main/java/com/yedu/backend/admin/application/dto/res/ScheduledClass.java
src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
src/main/java/com/yedu/backend/admin/application/usecase/AdminInfoUseCase.java
src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingRepository.java
src/main/java/com/yedu/backend/domain/matching/domain/service/ClassMatchingGetService.java
src/main/java/com/yedu/backend/global/exception/matching/MatchingNotSendStatusException.java
src/main/java/com/yedu/backend/global/exception/matching/constant/MatchingErrorCode.java

- 관련 테크스펙 링크 : https://www.notion.so/REST-API-1cbafa1037b28007bd8ffbbbf0512e53
- 매칭 전 상태가 '전송'이여야만 함으로 validation & exception 추가했습니다.
- accept count 계산하는 다른 부분에는 매칭상태 변경사항이 적용 안되있어 추가했습니다!
- /admin/details/matching/class/${applicationFormId} API에도 확정수업일시 응답필드 추가하였습니다

refactor : 상담 시작시 매칭상태 validation 추가  & accept count 미적용된 부분 반영

---

src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
src/main/java/com/yedu/backend/global/bizppurio/application/usecase/BizppurioParentsMessage.java

학부모 신청시 알림톡 전송 중단
영대님 요청으로 학부모 신청시 발송되는 알림톡을 중단하겠습니다

Hotfix : 알림톡 중단

---

src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
src/main/java/com/yedu/backend/global/event/publisher/BizppurioEventPublisher.java

학부모 알림톡 중단
영대님 요청으로 알림톡을 중단한 이후, main에 반영했으나 여기서 살아서 올라가게 되어 다시 활성화 되는 것을 방지하기 위해
마찬가지로 정지하여 PR올립니다!

fix : 학부모 알림톡 중단

---

api/src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleConfirmRequest.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
api/src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
api/src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
api/src/main/java/com/yedu/backend/global/discord/DiscordWebhookUseCase.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordMapper.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientProperties.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientTemplate.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookType.java

- 관련 테크스펙 링크 :  https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1cbafa1037b28007bd8ffbbbf0512e53&pm=s
- 디스코드 웹훅 메시지 상세화 
- 디스코드 웹훅  모듈 리팩토링 
-  enum값으로 메시지 관리 
-  웹훅 비동기로 변경
- 상담 후 진행 API - 첫 수업 시간 요청 스펙에서 제거 (사용하지 않음)
- 이전 PR에 리뷰 주신건은 아래에 코멘트 남기겠습니다! ( https://github.com/Y-edu/Y-edu-backend/pull/111#discussion_r2033510379 )
- application.yaml 수정 발생해서 갱신하였습니다~
- https://www.notion.so/application-yml-update-20250409-1c6afa1037b280ebbbe7f3dfea9d9b7a
- 수정사항 : webhook 설정 수정

feat : 웹훅 메시지 상세화

---

api/src/main/java/com/yedu/backend/bizppurio/application/mapper/BizppurioMapper.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientProperties.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientTemplate.java

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1cbafa1037b28007bd8ffbbbf0512e53&pm=s
디스코드 웹훅 발송시 간혈적으로 미발송되는것같아서 retry로직추가합니다!
application-dev.yaml파일에 
재시도횟수는 2회, 요청 간격은 3초정도로 지정할까싶습니다!

feat : webclient retry 로직 추가

---

api/src/main/java/com/yedu/backend/bizppurio/application/mapper/BizppurioMapper.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/java/com/yedu/backend/global/event/dto/ParentsClassInfoEvent.java
api/src/main/java/com/yedu/backend/global/event/mapper/EventMapper.java

학부모 상담 결과 공유 알림톡
- 선생님 결과 공유 완료시 학부모 상담 결과 공유 알림톡 전송
---
📋 전화상담 후 수업정보 전달 📋
애나  선생님
✅ 수업 시수 : 주 3회 50분, 75분, 100분
✅ 수업 시간 :
[ 월 14:00 부터 50분 ] 
[ 화 15:00 부터 50분 ] 
[ 수 14:00 부터 50분 ]
✅ 첫 수업 : 4월 2일 월요일 14:00
✅ 교재 : 워드마스터 
선생님과 전화 상담 시 확정한 수업 정보를 정리드릴게요. 
앞으로 잘 부탁드립니다 🙇🏻‍♀️
---
이런식으로 전송하기 위해서 작성한 것이고, 변수에 하나씩 넣은 것이 아닌, 여러가지를 조합해서 하나의 문자열로 만든 다음 변수에 넣었다보니 실제 동작 여부와 결과는 확인을 해보아야 알 것 같아요!

feat : 학부모 상담 결과 공유 알림톡

---

api/src/main/resources/db/migration/V4_202504161130__create_time_table.sql

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1d5afa1037b280088efbf971db4375d5&pm=s
- 작업을 위한 타임 테이블 생성

feat : timetable 관련 테이블 추가

---

api/build.gradle.kts
api/src/main/java/com/yedu/backend/domain/parents/application/dto/req/ApplicationFormTimeTableRequest.java
api/src/main/java/com/yedu/backend/domain/parents/application/dto/res/ApplicationFormTimeTableResponse.java
api/src/main/java/com/yedu/backend/domain/parents/application/mapper/ApplicationFormAvailableMapper.java
api/src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
api/src/main/java/com/yedu/backend/domain/parents/domain/entity/ApplicationForm.java
api/src/main/java/com/yedu/backend/domain/parents/domain/entity/ApplicationFormAvailable.java
api/src/main/java/com/yedu/backend/domain/parents/domain/repository/ApplicationFormAvailableRepository.java
api/src/main/java/com/yedu/backend/domain/parents/domain/service/ApplicationFormAvailableQueryService.java
api/src/main/java/com/yedu/backend/domain/parents/presentation/ParentsController.java
api/src/main/java/com/yedu/backend/global/exception/GlobalExceptionHandler.java
api/src/main/resources/db/migration/V4_202504171230__modify_timetable_application_form_column.sql

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1d5afa1037b280088efbf971db4375d5&pm=s
- 멘토링 style nullable변경
- application_form_id varchar로 변경 
- 과외 타임테이블 조회 API 개발 
- jarkata validation 추가 &  exception handler 추가
- 조회 API는 알림톡 링크에서는 토큰 / 어드인에서는 ID 로 통해 조회 가능하도록 개발했습니다!

feat : 과외 타임테이블 조회 API 개발

---

api/src/main/java/com/yedu/backend/domain/parents/application/mapper/ParentsMapper.java
api/src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherInfoUseCase.java
api/src/main/java/com/yedu/backend/domain/teacher/domain/aggregate/TeacherWithAvailable.java
api/src/main/java/com/yedu/backend/domain/teacher/domain/entity/TeacherAvailable.java
api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepository.java
api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java
api/src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherGetService.java

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1d5afa1037b280088efbf971db4375d5&pm=s
-  teacher_available inner join (어차피 시간없으면 발송안됨)
-  application_form_available 정보와 비교해서 교집합이 요일별로 주 n개 이상이면 true로 반환 

feat : 선생님 과외 공지 알림톡 발송 조건 수정 (타임테이블 주 n회 겹치는 경우에만 발송)

---

api/src/main/java/com/yedu/backend/admin/application/usecase/AdminManageUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/application/dto/req/MatchingTimeTableRequest.java
api/src/main/java/com/yedu/backend/domain/matching/application/dto/req/MatchingTimeTableRetrieveRequest.java
api/src/main/java/com/yedu/backend/domain/matching/application/dto/res/MatchingTimetableRetrieveResponse.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimeTableUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimetableUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
api/src/main/java/com/yedu/backend/domain/matching/domain/entity/MatchingTimetable.java
api/src/main/java/com/yedu/backend/domain/matching/domain/entity/constant/MatchingStatus.java
api/src/main/java/com/yedu/backend/domain/matching/domain/repository/MatchingTimetableRepository.java
api/src/main/java/com/yedu/backend/domain/matching/domain/service/MatchingTimetableCommandService.java
api/src/main/java/com/yedu/backend/domain/matching/domain/service/MatchingTimetableKeyStorage.java
api/src/main/java/com/yedu/backend/domain/matching/domain/service/MatchingTimetableQueryService.java
api/src/main/java/com/yedu/backend/domain/matching/presentation/MatchingTimetableController.java
api/src/main/java/com/yedu/backend/domain/matching/utils/KeyStorage.java
api/src/main/java/com/yedu/backend/global/exception/matching/MatchingTimetableAlreadyException.java
api/src/main/java/com/yedu/backend/global/exception/matching/constant/MatchingErrorCode.java
api/src/main/resources/db/migration/V4_202504182045__alter_classMatching_status.sql

- 관련 테크스펙 링크 : https://www.notion.so/1d8afa1037b2807a930af40890a1a9ee
- classMatching 테이블의 status에 '입금확인' 상태 추가
대기 -> 수락or거절 -> 전송 -> 입금확인 -> 매칭 이런식으로 진행될 것 같아요!'
- key관련 service를 하나 더 만들어야 했는데, KEY값 제외 모든 코드가 중복되어 중복 코드를 별도의 클래스로 뺐어요
토큰 기반 알림톡 링크 변경은, 알림톡을 우선 확인하고 진행하는게 낫지 않을까 싶어서 todo 로 처리해놨어요

feat : matchingTimetable 생성 및 조회 API추가

---

build.gradle.kts

- 코드 린트  도구 추가했습니다!
- 아래 통해 린트 적용 가능합니다!
```java
./gradlew spotlessApply  
```
- google java style 로 린트 되도록 수정하였는데, 구글께  tab 이 4 indent가 아니라 2 indent라서 보실떄 좀 불편하실수도잇을것같아여 꼭 구글 포맷팅이 아니여도되고, 일단 일관성있게 코드스타일유지하는게 좋지않을까싶어서 추가했습니다!
- 일단 일관성있게 린트 넣는게 코드 볼때 편안하지 않을까싶어서 추가했는데 의견부탁드려요!

refactor : code lint tool 추가

---

api/src/main/java/com/yedu/backend/domain/matching/application/mapper/ClassMatchingMapper.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassMatchingInfoUseCase.java

chore : lint 수정

---

api/src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
api/src/main/java/com/yedu/backend/domain/matching/domain/entity/constant/MatchingStatus.java
api/src/main/resources/db/migration/V4_202504182045__alter_classMatching_status_2.sql

fix : 매칭상태 수정

---

api/build.gradle.kts
api/src/main/java/com/yedu/backend/admin/application/dto/res/ProposalTeacherResponse.java
api/src/main/java/com/yedu/backend/admin/application/usecase/AdminManageUseCase.java
api/src/main/java/com/yedu/backend/admin/presentation/AdminController.java
api/src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassMatchingInfoUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassMatchingManageUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingController.java
api/src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java
api/src/main/java/com/yedu/backend/global/event/mapper/BizppurioEventMapper.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
shared/cache-support/src/main/java/com/yedu/cache/support/dto/TeacherNotifyApplicationFormDto.java
shared/cache-support/src/main/java/com/yedu/cache/support/storage/TeacherNotifyApplicationFormKeyStorage.java
shared/common/src/main/java/com/yedu/common/event/bizppurio/NotifyClassInfoEvent.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookType.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookUseCase.java
shared/discord-support/src/main/java/com/yedu/discord/support/listener/DiscordEventListener.java

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1dbafa1037b280cb885beed78703ba40&pm=s
- 선생님께 과외 공지시 토큰기반으로 동작하도록 수정하였습니다. 
- 테스트용으로 디코 웹훅하나 연결하였습니다!

feat : 선생님께 과외 공지시 토큰기반으로 요청받고,응답할수있도록 수정

---

api/src/main/java/com/yedu/backend/domain/teacher/application/dto/req/AvailableChangeTokenRequest.java
api/src/main/java/com/yedu/backend/domain/teacher/application/mapper/TeacherMapper.java
api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java
api/src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherController.java

- 관련 테크스펙 링크 : https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1dbafa1037b280cb885beed78703ba40&pm=s
- 선생님 가능 시간을 토큰 기반으로 갱신할수있도록 API 추가 
- 기존API는 어드민에서 사용될수있어 스펙변경안했습니다!

feat : 선생님 가능 시간 변경 토큰용 API 개발

---

api/src/main/java/com/yedu/backend/domain/matching/domain/entity/MatchingTimetable.java
shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookUseCase.java
shared/discord-support/src/main/java/com/yedu/discord/support/listener/DiscordEventListener.java

- 관련 테크스펙 링크 :
- 테이블 칼럼은 class_matching_id 인데, JPA 쿼리는 class_matching_class_matching_id 로 나가고있어 수정했습니다

fix : JPA 매핑 버그 수정

---

api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimetableUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/domain/service/MatchingTimetableCommandService.java
api/src/main/java/com/yedu/backend/global/event/publisher/EventPublisher.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/usecase/BizppurioParentsMessage.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/event/listener/BizppurioParentsMessageListener.java
shared/common/src/main/java/com/yedu/common/event/bizppurio/PayNotificationEvent.java

- 관련 테크스펙 링크 :  https://www.notion.so/list-e0e0be947a564f3794bc46f988352c73?p=1dbafa1037b280cb885beed78703ba40&pm=s
- 입금안내 알림톡 연동

feat : 학부모에게 입금안내 알림톡 연동

---

api/src/main/java/com/yedu/backend/domain/matching/application/dto/req/MatchingTimeTableRetrieveByTokenRequest.java
api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimetableUseCase.java
api/src/main/java/com/yedu/backend/domain/matching/presentation/MatchingTimetableController.java

- 관련 테크스펙 링크 : https://www.notion.so/API-1dbafa1037b280cb885beed78703ba40
- 토큰 기반 학부모 시간 조회 API
- classMatchingToken 사용

feat : 토큰 기반 학부모 시간 조회 API

---

shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java

- 소수점 출력 가능하도록 `DecimalFormat` 통해서 금액 출력하도록 수정

fix : 소수점 금액 안내되지 않는 부분 수정

---

shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java

- DecimalFormat 사용해서 소수점까지 출력
- 소수점 금액없으면 정수부분만 출력

fix : 학부모 입금안내시 금액 소수점 미노출되는 문제 수정

---

api/src/main/java/com/yedu/api/domain/parents/application/usecase/ParentsManageUseCase.java
api/src/main/java/com/yedu/api/domain/parents/domain/repository/ApplicationFormRepository.java
api/src/main/java/com/yedu/api/domain/parents/presentation/ParentsController.java

- add: find all field data
- add: resend duple session alarmtalk by admin

(250728) Fix: send duple session alarmtalk

---

api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java

Fix: maxRound calculate

---

api/src/main/java/com/yedu/api/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java

(250816) Fix: 일반휴강 횟수 차감 제거

---

api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java

Fix: 당일휴강, 무료보강 회차 0 업데이트, 당일 휴강 회차를 다음 회차로 업데이트

(250816) Fix: 당일휴강, 무료보강 회차 0 업데이트, 당일 휴강 회차를 다음 회차로 업데이트

---

api/src/main/java/com/yedu/api/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/java/com/yedu/api/domain/matching/domain/repository/ClassSessionRepository.java
api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java

(250816) Fix: 무료보강 회차 변경- 날짜변경시에도 반영

(250816) Fix: 무료보강 회차 변경- 날짜변경시에도 반영

---

api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java

(250824) Fix: compile error2

---

api/src/main/java/com/yedu/api/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/resources/graphql/schema.graphqls
consumer/src/main/java/com/yedu/consumer/consumer/ParentMessageConsumer.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/config/BizpurrioTemplate.java
shared/common/src/main/java/com/yedu/common/event/bizppurio/ParentCompleteTalkNotifyEvent.java
shared/rabbitmq-support/src/main/java/com/yedu/rabbitmq/support/RabbitMqProducer.java

feat : 학부모 과외 리뷰 알림톡 연동

---

api/src/main/java/com/yedu/api/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
api/src/main/java/com/yedu/api/domain/matching/domain/service/ClassSessionCommandService.java
api/src/main/java/com/yedu/api/domain/matching/domain/service/PaymentRequestService.java
api/src/main/java/com/yedu/api/global/config/AppConfig.java

(250829) Feat: 회차 과외 완료 요청시 결제 요청 API 반영
